FIREBASE_API_KEY = "AIzaSyAr3RChPqT89oy_dBakL7PO_qU03TTLE0k"

[FIREBASE_SERVICE_ACCOUNT]

type = "service_account"
project_id = "webap-6e49a"
private_key_id = "c0e8fd963a84b382decbb8c06785f2786aa58923"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDIL+ComB9bMuYb
ZeiH/an6aBBLb0ZMJ8npJHEeFmXQ/cobrLzSj9YtsjOsvYHyONPI2kgeeSZCGbSc
YqHJeW3n6mR+8klB3qGkwFMDWRdCS2ni016EgXkSamq6zEZ7kO2DHonSy1eQfZiD
sdRhju4DV9icl188+Tr8pujuHde3ysfckIEC9as3CzpCIqoB65UvG5tsFGEXvvLO
r5lsshn2sR89u8esjy3dfqTChj7MMMAquKhMze34N28AOKTci6K1z/5H1JfD2RxI
+wNCiQA1sF/0YlSVratQ5kbJ6MiitzxTiN8cjm9kZuSvSXCe8Bm3HsxrSNJwRzj3
JBnAHYW7AgMBAAECggEAA2Z2Hpb64rMsymatj5saPIPGUb8G8Xs0Mu6+ByCimRf+
dgA18tj47oIaM5htG8lQUOyNkLWbwJVW29h8Xq4z1N5xLODTqA1D2fG0V0MM90DN
qx8jpK+ITWzw+XxHxDM0KD0oDSRhYosSQJu60O9lu+PNl5dQnvoCwPuFdanxxJA4
VDlai49i7Ony1zElqoYKGqAcJK4aC4ga5sfHWsC4F+HiEE01PfQCijnilKu6UEFt
HvInoys9gj8dNz/BNsIkaQ7MOPlFc1NQISUiuFL0pNLS9O2s0n8DKVULWzR2OYfK
k1fJjc5olOdFEAB67FVa5zMDPv49mckZUOqPxZOCEQKBgQDpPHkVh2Af2quUmfvt
viyi9BSoJel9V/X2HVo0cn8FbE1FBEMcCP4r/thc6nt2Q5V+X21UQ0vym0WLcpWe
MSqXsBsaIYp6O1L7+0INOeUUSGmZlFONVnBoJPwzoLfyWzGULadaPBj94fFWhVCd
HYEBCE8+URniCgFfGuqCm7ReCwKBgQDbuac+z5Q0yHPJuwMVastV4vlvWvZTt1F0
OqnhCpZjUmWNI/uhhXVfpSKC5Wy3v9JnFFMNNQoWATvB+FoOVQ6FIY/0QxN5uxiX
jhe92kKStY2oWARBvunIoX++s/IR9aXAkjEwzLCIx8EIfHwVDYoaNBmyNPp7uEBO
6e/DfuE1EQKBgFE5PRWxQll1hoFGqsRdkR/ijnsMUObUxhRCnpJbOT8DO1mIpXJS
82kQ4/pfskU6Pgp3YxSQJxfC2RI6Aj7H8oRG0PllqtrsY/baxmLiwZMxsIzKadpz
usuZ7bZxBv5AoeBvkbNL8IwhrjEqViuRBcb9RNN33OKqB1Y+gmKfpM2HAoGARE3p
XNBAvUvXGs4E/mJthWyCqAg57Ppe2uflqWyWJZgWs5KNBcAsJah7Gv/hFRoPeTXL
P57OXNrTTdA7hpsQYXh2fLNhWYU89tgYL0+rRFomCEAcSqfjmxgBUzIzPTwE4+FO
Y2IuOscGDfJMzGqiFNU/a7OmblFvxFhazYYi0lECgYEAn4WIRH7uIEBRhajPWWgg
bD1aWCrsiCJtBz4J89dNDQ1Cr2sqGRfIY9Mp2XdgE70SXo5F7ce8ybT5aZPCRHT9
xVNCYKc33+06qCOuBsIMMakI2STxRjYXBsE8/ZrXBfl2BFFh6nmdYstAJ/FFo6QN
tmYP4juK0ul0xRnlkFWGE30=
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-fbsvc@webap-6e49a.iam.gserviceaccount.com"
client_id = "100204266031113174768"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40webap-6e49a.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
